drop table IF EXISTS answer;
drop table IF EXISTS question;

create table question (
      id integer generated by default as identity,
      sentence varchar(510),
      month integer,
      day integer,
      primary key (id)
);

create table answer (
    id integer generated by default as identity,
    answer varchar(510),
    year integer,
    created_time timestamp,
    updated_time timestamp,
    question_id integer,
    primary key (id)
);

-- INSERT INTO question (id, sentence, month, day) VALUES
--     (1, '질문1', 12, 7),
--     (2, '질문22222 22222222222222222222 22222222222222 22222222222 222222222222', 12, 8);
--
-- INSERT INTO answer (id, answer, question_id, created_time, updated_time) VALUES
--     (1, '답변1', 1, '2021-10-08T16:38:10', '2021-10-08T16:38:10'),
--     (2, '답변2', 1, '2021-10-08T16:38:10', '2021-10-08T16:38:10'),
--     (3, '답변3', 1, '2021-10-08T16:38:10', '2021-10-08T16:38:10'),
--     (4, '답변4', 1, '2021-10-08T16:38:10', '2021-10-08T16:38:10');